name: API Tests Pipeline Kata

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      - name: Instalar dependencias
        run: mvn install

      - name: Ejecutar pruebas con TestNG
        run: mvn test -DsuiteXmlFile=src/test/java/resources/testng.xml

      - name: Generar reporte de pruebas
        run: mvn surefire-report:report

      - name: Guardar reportes como artefactos
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports
